create table employee (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	gender VARCHAR(7) NOT NULL,
	email VARCHAR(120),
	date_of_birth DATE NOT NULL
);
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Sallyanne', 'Hakonsson', 'Female', 'shakonsson0@google.pl', '1991/08/07');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Janel', 'Muschette', 'Female', 'jmuschette1@mail.ru', '1985/11/10');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Harald', 'Burtt', 'Male', 'hburtt2@live.com', '1976/02/23');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Caz', 'Luthwood', 'Male', 'cluthwood3@webmd.com', '1994/08/18');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Alicea', 'Crosston', 'Male', null, '1977/02/01');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Bronnie', 'Dielhenn', 'Male', 'bdielhenn5@last.fm', '1982/01/05');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Noami', 'Uttley', 'Female', null, '1982/05/27');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Idaline', 'Mewrcik', 'Female', null, '1978/12/14');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Chet', 'Boutwell', 'Male', 'cboutwell8@shinystat.com', '1979/09/30');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Fletcher', 'Minchindon', 'Male', null, '1988/06/14');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Cathryn', 'Sherratt', 'Female', null, '1991/06/05');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Adelind', 'Scallan', 'Female', 'ascallanb@cbc.ca', '1989/05/16');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Fabian', 'Rodolphe', 'Male', 'frodolphec@issuu.com', '1976/11/24');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Clive', 'Lammerts', 'Male', 'clammertsd@mashable.com', '1986/02/07');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Hansiain', 'Withringten', 'Male', 'hwithringtene@behance.net', '1984/05/02');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Hiram', 'MacLeod', 'Male', 'hmacleodf@studiopress.com', '1988/03/15');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Zenia', 'Hasney', 'Female', null, '1985/01/13');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Padriac', 'Towell', 'Male', 'ptowellh@is.gd', '1976/09/13');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Brand', 'Marcum', 'Male', 'bmarcumi@diigo.com', '1981/03/14');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Davey', 'Wray', 'Male', 'dwrayj@tuttocitta.it', '1984/04/08');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Lincoln', 'Dupree', 'Male', 'ldupreek@miibeian.gov.cn', '1981/11/15');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Zacharias', 'Byrch', 'Male', null, '1977/07/24');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Jedd', 'Craigheid', 'Male', 'jcraigheidm@netlog.com', '1976/01/17');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Jordanna', 'Roskelley', 'Female', 'jroskelleyn@sourceforge.net', '1986/04/05');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Abey', 'Bucknall', 'Male', 'abucknallo@nhs.uk', '1979/05/02');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Grady', 'Fowls', 'Male', null, '1989/07/22');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Corrie', 'Wordley', 'Male', 'cwordleyq@chicagotribune.com', '1978/03/20');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Ced', 'Mariaud', 'Male', 'cmariaudr@google.com.hk', '1983/03/20');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Marlow', 'Hansford', 'Male', 'mhansfords@cdc.gov', '1986/11/27');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Ally', 'Sommerton', 'Female', 'asommertont@altervista.org', '1982/03/03');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Herve', 'Ebbett', 'Male', 'hebbettu@gravatar.com', '1976/08/15');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Janenna', 'Conelly', 'Female', null, '1980/06/13');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Libbey', 'Glew', 'Female', 'lgleww@sciencedirect.com', '1975/10/20');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Emili', 'Tillard', 'Female', 'etillardx@jugem.jp', '1992/02/24');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Whitney', 'Fawkes', 'Male', null, '1981/10/23');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Adelina', 'Orr', 'Female', null, '1984/02/26');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Delphine', 'De Domenicis', 'Female', 'ddedomenicis10@hatena.ne.jp', '1982/04/19');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Niels', 'Peschmann', 'Male', null, '1982/05/04');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Cindie', 'Fiddeman', 'Female', 'cfiddeman12@disqus.com', '1991/08/25');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Val', 'Scothorne', 'Male', 'vscothorne13@globo.com', '1982/11/04');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Emmeline', 'Tremberth', 'Female', null, '1979/09/24');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Hermann', 'Growcott', 'Male', null, '1981/10/02');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Brendin', 'Cohane', 'Male', 'bcohane16@ebay.co.uk', '1987/03/05');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Vivien', 'Elgram', 'Female', null, '1991/10/03');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Myranda', 'Telfer', 'Female', 'mtelfer18@gov.uk', '1990/09/28');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Bryna', 'Dixey', 'Female', 'bdixey19@shutterfly.com', '1988/06/29');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Ally', 'Howsego', 'Female', 'ahowsego1a@admin.ch', '1986/03/08');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Haywood', 'Rubury', 'Male', 'hrubury1b@noaa.gov', '1992/09/21');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Sarah', 'Lydden', 'Female', 'slydden1c@jimdo.com', '1976/03/31');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Engelbert', 'Hutsby', 'Male', 'ehutsby1d@newyorker.com', '1985/08/05');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Vinny', 'Dominik', 'Female', 'vdominik1e@google.ca', '1986/02/16');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Jeffrey', 'Howson', 'Male', 'jhowson1f@ihg.com', '1981/09/07');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Nyssa', 'Pencot', 'Female', 'npencot1g@fc2.com', '1981/08/20');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Gonzalo', 'Itzcak', 'Male', 'gitzcak1h@businesswire.com', '1984/03/08');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Lorant', 'Moloney', 'Male', 'lmoloney1i@virginia.edu', '1989/06/18');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Amby', 'Sale', 'Male', 'asale1j@1688.com', '1982/12/21');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Berta', 'Threadgould', 'Male', null, '1994/05/13');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Minny', 'Pirdue', 'Female', 'mpirdue1l@vinaora.com', '1991/11/11');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Mart', 'Girogetti', 'Male', 'mgirogetti1m@sun.com', '1988/07/18');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Nathanial', 'Carmody', 'Male', 'ncarmody1n@mac.com', '1985/10/13');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Esra', 'McGhie', 'Male', null, '1986/03/11');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Spense', 'Annesley', 'Male', null, '1981/04/01');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Nevil', 'Rome', 'Male', 'nrome1q@princeton.edu', '1991/11/17');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Libbey', 'Steet', 'Female', 'lsteet1r@cnn.com', '1987/11/11');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Ced', 'Camois', 'Male', 'ccamois1s@acquirethisname.com', '1980/10/22');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Erick', 'Masterton', 'Male', 'emasterton1t@washingtonpost.com', '1994/09/18');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Arv', 'Pinkett', 'Male', 'apinkett1u@comsenz.com', '1994/03/12');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Jacintha', 'Litherborough', 'Female', 'jlitherborough1v@apple.com', '1984/02/06');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Carri', 'Reiners', 'Male', 'creiners1w@seattletimes.com', '1983/01/19');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Johnathan', 'Terrey', 'Male', 'jterrey1x@washington.edu', '1977/06/23');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Bowie', 'Dent', 'Male', 'bdent1y@mozilla.org', '1980/05/24');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Dud', 'Frankema', 'Male', 'dfrankema1z@yelp.com', '1987/12/27');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Eugene', 'Climo', 'Male', 'eclimo20@xinhuanet.com', '1987/09/30');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Aurore', 'Shadwick', 'Female', 'ashadwick21@themeforest.net', '1977/03/06');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Cad', 'Izkovitch', 'Male', null, '1987/02/16');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('La verne', 'Blake', 'Female', null, '1982/09/21');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Antonia', 'Larkings', 'Female', 'alarkings24@bloomberg.com', '1976/08/10');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Maynard', 'Adamowitz', 'Male', null, '1992/10/14');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Carmelina', 'Erricker', 'Female', 'cerricker26@cdc.gov', '1977/11/19');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Jimmy', 'Viel', 'Male', 'jviel27@histats.com', '1988/08/19');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Minda', 'Larciere', 'Female', null, '1994/04/19');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Ange', 'Dinnage', 'Male', 'adinnage29@homestead.com', '1977/09/30');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Rodge', 'Undrell', 'Male', 'rundrell2a@army.mil', '1981/06/01');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Dilly', 'Gregs', 'Male', 'dgregs2b@devhub.com', '1991/04/09');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Orville', 'Le Huquet', 'Male', null, '1986/06/26');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Paulita', 'Dumbare', 'Female', 'pdumbare2d@who.int', '1994/11/14');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Dehlia', 'Stelfax', 'Female', 'dstelfax2e@mapy.cz', '1992/02/21');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Iolande', 'Dummer', 'Female', 'idummer2f@sun.com', '1978/11/09');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Sallie', 'Feathersby', 'Female', 'sfeathersby2g@live.com', '1983/01/22');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Jen', 'Provest', 'Female', 'jprovest2h@geocities.jp', '1988/07/26');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Eddie', 'Sewley', 'Male', 'esewley2i@aboutads.info', '1978/06/18');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Cory', 'Escritt', 'Male', null, '1983/02/17');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Keslie', 'Eggins', 'Female', 'keggins2k@plala.or.jp', '1987/04/02');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Rosanne', 'Sketh', 'Male', 'rsketh2l@pinterest.com', '1975/01/27');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Tomaso', 'Load', 'Male', null, '1993/10/03');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Rosanne', 'Fearneley', 'Female', null, '1987/08/11');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Bo', 'Archley', 'Male', 'barchley2o@hud.gov', '1978/04/24');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Warren', 'Beams', 'Male', 'wbeams2p@wikipedia.org', '1990/07/11');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Thane', 'Howling', 'Male', 'thowling2q@gmpg.org', '1980/10/06');
insert into employee (first_name, last_name, gender, email, date_of_birth) values ('Otha', 'Proswell', 'Male', 'oproswell2r@bbc.co.uk', '1982/11/26');
